# Generated by Django 3.0.2 on 2020-08-12 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_auto_20200812_1702'),
    ]

    operations = [
        migrations.RenameField(
            model_name='token',
            old_name='token',
            new_name='key',
        ),
    ]
