# Generated by Django 3.0.2 on 2020-09-20 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0009_auto_20200917_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='limitOfMember',
            field=models.IntegerField(default=100),
        ),
    ]
