# Generated by Django 3.0.2 on 2020-09-20 18:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0010_contest_limitofmember'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='registerTimeUp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
