# Generated by Django 3.0.2 on 2020-09-22 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0012_auto_20200920_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='studentId',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
