# Generated by Django 3.0.2 on 2020-10-05 11:40

from django.db import migrations, models
import django.db.models.deletion
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0015_auto_20201005_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rsrvproject',
            name='contest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.Contest'),
        ),
        migrations.AlterField(
            model_name='rsrvproject',
            name='intro',
            field=mdeditor.fields.MDTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='rsrvtimeavailable',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='database.RsrvProject'),
        ),
    ]
